/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj009_radiobutton;

import javax.swing.JOptionPane;

/**
 *
 * @author 182210104
 */
public class RadioButtonFrame extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonFrame
     */
    public RadioButtonFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEsporte = new javax.swing.ButtonGroup();
        jlEsporte = new javax.swing.JLabel();
        jrbVoleibol = new javax.swing.JRadioButton();
        jrbBasketbol = new javax.swing.JRadioButton();
        jbtnTestarEsporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setFont(new java.awt.Font("Adobe Arabic", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 102));

        jlEsporte.setForeground(new java.awt.Color(0, 204, 204));
        jlEsporte.setText("Esporte");

        bgEsporte.add(jrbVoleibol);
        jrbVoleibol.setForeground(new java.awt.Color(0, 204, 204));
        jrbVoleibol.setSelected(true);
        jrbVoleibol.setText("Voleibol");
        jrbVoleibol.setActionCommand("Voleibol");
        jrbVoleibol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVoleibolActionPerformed(evt);
            }
        });

        bgEsporte.add(jrbBasketbol);
        jrbBasketbol.setForeground(new java.awt.Color(0, 204, 204));
        jrbBasketbol.setText("Basketbol");
        jrbBasketbol.setActionCommand("Basketbol");

        jbtnTestarEsporte.setBackground(new java.awt.Color(0, 0, 0));
        jbtnTestarEsporte.setForeground(new java.awt.Color(0, 204, 204));
        jbtnTestarEsporte.setText("TestarEsporte");
        jbtnTestarEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestarEsporteActionPerformed(evt);
            }
        });
        jbtnTestarEsporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnTestarEsporteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jlEsporte))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbBasketbol)
                            .addComponent(jrbVoleibol)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jbtnTestarEsporte)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlEsporte)
                .addGap(38, 38, 38)
                .addComponent(jrbVoleibol)
                .addGap(42, 42, 42)
                .addComponent(jrbBasketbol)
                .addGap(46, 46, 46)
                .addComponent(jbtnTestarEsporte)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testarRadio(){
        Proj009_RadioButton p = new Proj009_RadioButton();
        p.setEsporte(bgEsporte.getSelection().getActionCommand());
        
        JOptionPane.showMessageDialog(
        this,
                "Você escolheu " + p.getEsporte()+"!");
    }
    private void jrbVoleibolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVoleibolActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrbVoleibolActionPerformed

    private void jbtnTestarEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestarEsporteActionPerformed
        // TODO add your handling code here:
        testarRadio();
        
    }//GEN-LAST:event_jbtnTestarEsporteActionPerformed

    private void jbtnTestarEsporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnTestarEsporteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==keyEvent.VK_ENTER){
            testarRadio();
        }
        
    }//GEN-LAST:event_jbtnTestarEsporteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEsporte;
    private javax.swing.JButton jbtnTestarEsporte;
    private javax.swing.JLabel jlEsporte;
    private javax.swing.JRadioButton jrbBasketbol;
    private javax.swing.JRadioButton jrbVoleibol;
    // End of variables declaration//GEN-END:variables
}
